// Generated by Melange
'use strict';


function MonadOps(M) {
  return {
          $$return: M.$$return,
          $great$great$eq: M.bind
        };
}

exports.MonadOps = MonadOps;
/* No side effect */
